version: "2.1"
services:
     webserver:
          build:
               context: ./docker
               dockerfile: frontend.Dockerfile
          container_name: syno_downloadlist_frontend
          ports:
               - "9000:80"
          environment:
               - SYNOLOGY_HOST=192.168.1.27
               - SYNOLOGY_PORT=5000
               - SYNOLOGY_USERNAME=bmosley
               - SYNOLOGY_PASSWORD=DricasM4x
               - IPLOOKUP_HOST=${SYNOLOGY_IPLOOKUP_HOST}
               - IPLOOKUP_PORT=8080
          links:
               - ipaddress_lookup
     ipaddress_lookup:
          build:
               context: ./docker
               dockerfile: backend.Dockerfile
          container_name: syno_downloadlist_iplookup
          ports:
               - "3012:8080"
